### ISSUE TITLE
Register Activity Bug

### ISSUE THREAD

**Issue by JEVietti** [willgoishi/DealBreaker#1]
A bug occurs if when you set your username and hit enter on the onscreen or regular keyboard, the text disappears, and even when re-entering the text and registering without hitting enter after, it creates a user in the Firebase hash table, but doesn't add the user to the Database under users like it should. However if you never hit enter on the username EditText field it works as intended.

**Comment by AndresFelipeVargas** [comment]
Fixed the issue. The problem was that I did not specify the keyboard type for the username field on android.  Added the following: 
android:inputType="textPersonName"
This changes the keyboard and changes the enter key to next field key.
